name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  collection:
  decimal:
  dio:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  flutter_svg:
  flutter_web_plugins:
    sdk: flutter
  go_router:
  http:
  intl:
  json_annotation:
  riverpod_annotation:
  shared_preferences:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_gen_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  json_serializable:
  riverpod_generator:
  riverpod_lint:
  taptest: ^0.0.5
    # path: ../taptest
  taptest_runtime: ^0.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - path: assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans.ttf

flutter_gen:
  integrations:
    flutter_svg: true
