name: taptest
description: "Lightning-fast Flutter testing framework for comprehensive E2E and granular tests with snapshot support."
version: 0.0.12
homepage: https://taptest.dev
repository: https://github.com/chris-rutkowski/taptest

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.0
  device_info_plus: ^12.0.0
  fake_http_client: ^2.0.0
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  meta: ^1.16.0
  path: ^1.8.0
  platform: ^3.0.0
  qr: ^3.0.0
  taptest_runtime: ^0.0.4
    # path: ../taptest_runtime

dev_dependencies:
  http: 1.5.0
  flutter_lints:
  go_router: ">=8.0.0 <17.0.0"

flutter:
