name: taptest
description: "Lightning-fast Flutter testing framework for comprehensive E2E and granular tests with snapshot support."
version: 0.0.4
homepage: https://taptest.dev
repository: https://github.com/chris-rutkowski/taptest/tree/main/taptest

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  crypto:
  device_info_plus:
  fake_http_client:
  file:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  meta:
  path:
  platform:
  qr:
  taptest_runtime: ^0.0.3
    # path: ../taptest_runtime

dev_dependencies:
  flutter_lints:
  go_router:

flutter:
