name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  test:
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Flutter version
      id: flutter_version
      run: echo "version=$(cat flutter-version.txt)" >> $GITHUB_OUTPUT

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.flutter_version.outputs.version }}
        cache: true

    - name: Get package dependencies
      run: flutter pub get

    - name: Get example dependencies
      run: flutter pub get
      working-directory: ./example

    - name: Run package tests
      run: flutter test test

    - name: Run example tests
      run: flutter test test
      working-directory: ./example

    - name: Upload snapshot failures
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failures
        path: |
          example/test/failures
        retention-days: 1
